org.gradle.jvmargs=-Xms256m -Xmx4g -XX:MaxMetaspaceSize=1g -XX:ReservedCodeCacheSize=256m -XX:MaxDirectMemorySize=512m -Xss1m -Dfile.encoding=UTF-8
org.gradle.workers.max=3
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.daemon=false
org.gradle.vfs.watch=false
org.gradle.internal.instrumentation.agent=false
android.useAndroidX=true
android.enableJetifier=false
kotlin.code.style=official
kotlin.compiler.execution.strategy=daemon
kotlin.daemon.jvmargs=-Xms256m -Xmx2g -XX:MaxMetaspaceSize=1g -XX:ReservedCodeCacheSize=128m -XX:MaxDirectMemorySize=256m -Xss1m
kotlin.incremental=true
android.nonTransitiveRClass=true
